---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels: 
   app: ci-cd
   author: yasin
spec: 
  containers:
    - name: myjenkin
      image: jenkins/jenkins
      ports: 
       - containerPort: 8080
         hostPort: 1111
...

