---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels:
    author: yasin
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector: 
    app: redis-app
...
