---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: yasin
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector:
    app: result-app
...
